# Generated by Django 5.0.1 on 2024-01-22 14:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchName', models.CharField(max_length=50)),
                ('course_duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Course duration must be greater than or equal to 1.'), django.core.validators.MaxValueValidator(limit_value=5, message='Course duration must be less than or equal to 5.')])),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=50)),
                ('branchName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('1st-Year', '1st-Year'), ('2nd-Year', '2nd-Year'), ('3rd-Year', '3rd-Year'), ('4th-Year', '4th-Year'), ('5th-Year', '5th-Year')], max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('regno', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('year', models.CharField(choices=[('1st-Year', '1st-Year'), ('2nd-Year', '2nd-Year'), ('3rd-Year', '3rd-Year'), ('4th-Year', '4th-Year'), ('5th-Year', '5th-Year')], max_length=50)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.branch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.department')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('year', models.CharField(choices=[('1st-Year', '1st-Year'), ('2nd-Year', '2nd-Year'), ('3rd-Year', '3rd-Year'), ('4th-Year', '4th-Year'), ('5th-Year', '5th-Year')], max_length=50)),
                ('description', models.TextField(null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.branch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.department')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.program')),
            ],
        ),
    ]
