# Generated by Django 5.0.1 on 2024-01-21 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolled_programs',
        ),
    ]
