# Generated by Django 5.0.1 on 2024-08-23 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRuntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timerunned', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.video')),
            ],
        ),
    ]
