# Generated by Django 5.0.1 on 2024-10-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_videoruntime'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='img',
            field=models.ImageField(null=True, upload_to='SubjectImage/'),
        ),
    ]
