# Generated by Django 5.0.1 on 2024-02-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
