# Generated by Django 5.0.1 on 2024-10-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_subject_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='img',
            field=models.ImageField(null=True, upload_to='Topic/'),
        ),
    ]
