# Generated by Django 5.0.1 on 2024-02-15 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_video_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='viewby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student'),
        ),
    ]
