# Generated by Django 5.0.1 on 2024-02-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_video_viewby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='viewby',
        ),
        migrations.AddField(
            model_name='video',
            name='viewby',
            field=models.ManyToManyField(to='home.student'),
        ),
    ]
