# Generated by Django 5.0.1 on 2024-02-15 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_video_viewby_video_viewby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='view',
        ),
    ]
