# Generated by Django 5.0.1 on 2024-02-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_video_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='like',
        ),
        migrations.AlterField(
            model_name='video',
            name='viewby',
            field=models.ManyToManyField(related_name='videos_viewed', to='home.student'),
        ),
        migrations.AddField(
            model_name='video',
            name='like',
            field=models.ManyToManyField(related_name='videos_liked', to='home.student'),
        ),
    ]
