# Generated by Django 5.0.1 on 2024-04-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_video_like_alter_video_viewby_video_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='videos_liked', to='home.student'),
        ),
        migrations.AlterField(
            model_name='video',
            name='viewby',
            field=models.ManyToManyField(blank=True, null=True, related_name='videos_viewed', to='home.student'),
        ),
    ]
